### ISSUE TITLE
Decide on Project Name

### ISSUE THREAD

**Issue by commul-dev** [commul/fromthepage#1]
The final project (likely) needs a different name than the original. Suggestions are as follows:
(note that a long name would need a *gloss* and an *abbreviation*.)

Suggested name (and gloss) | Supporter
------------ | -------------
transanno | @iiegn 
xml_from_page | 
OTHERS COME HERE |

 @kreetrapper @lnicolas @nadezdaalexandrovna @seewind

**Comment by nadezdaalexandrovna** [comment]
"transanno" is the name of the project

**Comment by iiegn** [comment]
This issue was moved to commul/fromthepage#1
