### ISSUE TITLE
Set up persistent storage

### ISSUE THREAD

**Issue by iiegn** [commul/fromthepage#13]
`transcanno` seems to need persistent storage, i.e. space where it persistently stores data besides the database:
```
http://kommul.eurac.edu/transcanno/images/uploaded/for_tests/page_0001_thumb.jpg 404 (Not Found)
```
@nadezdaalexandrovna please fill in path(s) that hold content that **must not** be deleted.

**Comment by nadezdaalexandrovna** [comment]
http://kommul.eurac.edu/transcanno/images
http://kommul.eurac.edu/transcanno/public
http://kommul.eurac.edu/transcanno/app
http://kommul.eurac.edu/transcanno/bin
http://kommul.eurac.edu/transcanno/config
http://kommul.eurac.edu/transcanno/db
http://kommul.eurac.edu/transcanno/lib
http://kommul.eurac.edu/transcanno/selenium_tests_when_app_is_running
http://kommul.eurac.edu/transcanno/spec
http://kommul.eurac.edu/transcanno/stylesheets
http://kommul.eurac.edu/transcanno/test_data
http://kommul.eurac.edu/transcanno/vendor

**Comment by iiegn** [comment]
oh dear, this seems a bit excessive - i make it more precise:
we need to configure **a minimal set** of persistent storage locations for data that - upon deletion - cannot or will not be automatically re-generated. ideally, this should be **a single** location.

from a first glance `http://kommul.eurac.edu/transcanno/selenium_tests_when_app_is_running`, for example, seems to fall under the category *who cares*...

**Comment by nadezdaalexandrovna** [comment]
a single location: http://kommul.eurac.edu/transcanno/images

And the site does not work correctly, there are errors when I try to navigate through it.

**Comment by kreetrapper** [comment]
images are in `/opt/transcanno/public/images`.
Is this all that should be kept in persistent storage? What about the css (and javascript?) that gets created sometimes due to user actions?

**Comment by nadezdaalexandrovna** [comment]
Yes, the javascript and css have to be kept, too. They are in app/assets/javascripts and app/assets/stylesheets

**Comment by kreetrapper** [comment]
Fixed by https://gitlab.inf.unibz.it/commul/docker/transcanno/commit/c3997c9e75503cf12458457e09e236d8aa4d932e
Should be tested before being used in production.

**Comment by iiegn** [comment]
closing this ticket because
 - infrastructure related things are now part of the https://gitlab.inf.unibz.it/commul/docker/transcanno/
 - the issue has (mostly) been solved
