### ISSUE TITLE
Set up minimal Travis CI test

### ISSUE THREAD

**Issue by iiegn** [commul/fromthepage#2]
This is only supposed to automate the deployment of a/the development branch.

**Comment by kreetrapper** [comment]
This looks like a good starting point. https://blog.stackahoy.io/a-guide-to-automated-docker-deployments-w-gitlab-ci-510966dd6022

**Comment by iiegn** [comment]
fixed in https://gitlab.inf.unibz.it/commul/docker/transcanno/commit/ffefc9513e7050a7bdb35f55cf3d10bbdc126997
