### ISSUE TITLE
a mysql query to execute on the transcanno database

### ISSUE THREAD

**Issue by nadezdaalexandrovna** [commul/fromthepage#21]
Alex, sorry to disturb you, could you please execute this query on the transcanno production database when you are back to Bolzano? Thank you!

update `users` set created_at='2017-12-13 07:16:35' where login='collection_owner'

**Comment by nadezdaalexandrovna** [comment]
I mean, when you are back to Bolzano :)

**Comment by kreetrapper** [comment]
done
