### ISSUE TITLE
Search function 

### ISSUE THREAD

**Issue by seewind** [commul/fromthepage#49]
The search function adds strange wildcards around the search string. Why is this?
Why can one not search for "work" names?

**Comment by nadezdaalexandrovna** [comment]
I have updated the search function in the version that is currently only on my computer. There are no more wildcards. But it only searches the transcription text and the header categories. Why do you want to search "work" names? You just do Ctrl+F and search for them in the browser on the Overview tab of a collection.

**Comment by seewind** [comment]
Sounds good. It was not clear to me what the search function is supposed to do and what not. I am fine if it does not search the work names. However, it's good if the wildcards are no longer there! Thank you
