### ISSUE TITLE
Page navigation in transcription mode. 

### ISSUE THREAD

**Issue by seewind** [commul/fromthepage#55]
The page navigation pane in the transcription mode is aligned dynamically. This means that with certain screen resolutions it gets partly hidden by other content. 
This should not happen. It should always be aligned on the right side, without overlap possibility, as are the button "Transcription finished" and the "Use advanced mode" option.

**Comment by nadezdaalexandrovna** [comment]
Addressed in commit 16efa7ac153378000d4a69820f07a0ad329a7ea9
