### ISSUE TITLE
Add Export possibility to work view

### ISSUE THREAD

**Issue by seewind** [commul/fromthepage#58]
Is it possible to add the Export function also directly to the works/pages ?

![image](https://user-images.githubusercontent.com/20414218/75750989-add7de00-5d25-11ea-8f70-66130f0b41b5.png)

**Comment by nadezdaalexandrovna** [comment]
Yes. Addressed in commit b48e9a44dd0e39e0a97f3bc7488d7826bebbd33b
I have added the Export function that exports the work in TEI-XML format.
