### ISSUE TITLE
Problems with user rights and hidden options

### ISSUE THREAD

**Issue by seewind** [commul/fromthepage#59]
Usually it is not possible to export, when you are not logged in and you are not the owner. However, if you know the URL you can still accses the exports.

![image](https://user-images.githubusercontent.com/20414218/75757987-a5869f80-5d33-11ea-9791-6fc794a9086c.png)

**Comment by nadezdaalexandrovna** [comment]
Addressed in commit abbaf3e907dc26cc996f6bc715ee01259e346791
