### ISSUE TITLE
Allow the user to delete previous versions of the transcription

### ISSUE THREAD

**Issue by nadezdaalexandrovna** [commul/fromthepage#6]
Create a button on the transcription page allowing the transcriber to delete previous versions of the transcription.

**Comment by nadezdaalexandrovna** [comment]
The button "Transcription finished" has been created on the "Transcribe" page. It deletes all the previous versions of the transcription from the page_versions page and only registers the last one in this table. It also does the same things as the "Save changes" button.

**Comment by iiegn** [comment]
This issue was moved to commul/fromthepage#6
