### ISSUE TITLE
Optimize search options

### ISSUE THREAD

**Issue by seewind** [commul/fromthepage#61]
The search option display needs a revision. 
Not all of them have a checkbox. The checkboxes should be in the beginning of the line. There should be a header telling you that the following options are settings to restrict the search function. (e.g. Advanced search, Search options, or Filter search)

![image](https://user-images.githubusercontent.com/20414218/75758432-660c8300-5d34-11ea-8a2e-b795cbefe896.png)

**Comment by nadezdaalexandrovna** [comment]
Addressed in commit 0b8c6e7d957dfaceb6451f3b76d6d212a39f8ad4
