### ISSUE TITLE
Text export adds text that does not belong there

### ISSUE THREAD

**Issue by seewind** [commul/fromthepage#62]
This work

![image](https://user-images.githubusercontent.com/20414218/75759936-a5d46a00-5d36-11ea-8fdb-f759930ab65c.png)

results in this export

Work_title:
download-merlin

Work_description:
download-merlin

Page_title:
1
Page_text:
 

Page_title:
2
Page_text:
 

Page_title:
3
Page_text:
 3haha Merlin third page transcription.

I assume, the "3haha" should not be there. Also it is not necessary to have so many blank lines. This makes parsing the text harder.

**Comment by nadezdaalexandrovna** [comment]
Addressed in commit a45861ee8c8214b89641b8eb1d9b6bc2480f0a0a
