### ISSUE TITLE
Allow the user to go back to the previous version of the transcription

### ISSUE THREAD

**Issue by nadezdaalexandrovna** [commul/fromthepage#7]
Add a button on the Versions page that lets the user choose the version that will become the main version of the transcription.

**Comment by nadezdaalexandrovna** [comment]
Created a button on the Versions page "Work on this version" allowing the user to choose the version he want to work on. If he pushes it, the version is registered to the pages table and becomes the main version.

**Comment by iiegn** [comment]
This issue was moved to commul/fromthepage#7
